library(dplyr)
mecha_cars<- read.csv(file ="MechaCar_mpg.csv")
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data=mecha_cars)
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data=mecha_cars))
suspension_cars<- read.csv(file ="Suspension_Coil.csv")
total_summary <- suspension_cars %>% summarize(Mean=mean(PSI),Median=median(PSI),variance=var(PSI),SD=sd(PSI))
lot_summary <- suspension_cars %>% group_by(Manufacturing_Lot)%>% summarize(Mean=mean(PSI),Median=median(PSI),variance=var(PSI),SD=sd(PSI))
t.test(suspension_cars$PSI,mu = 1500)
t.test(subset(suspension_cars, Manufacturing_Lot=="Lot1")$PSI,mu=1500)
t.test(subset(suspension_cars, Manufacturing_Lot=="Lot2")$PSI,mu=1500)
t.test(subset(suspension_cars, Manufacturing_Lot=="Lot3")$PSI,mu=1500)
